//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 02.07.2014 20:57:11
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace SocialLogger
{

    /// <summary>
    /// There are no comments for SocialLogger.LogEntry in the schema.
    /// </summary>
    [Table(Name = @"LogEntries")]
    public partial class LogEntry : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private System.DateTime _StartAt;

        private System.Nullable<System.DateTime> _EndAt;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnStartAtChanging(System.DateTime value);
        partial void OnStartAtChanged();
        partial void OnEndAtChanging(System.Nullable<System.DateTime> value);
        partial void OnEndAtChanged();
        #endregion

        public LogEntry()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "integer NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for StartAt in the schema.
        /// </summary>
        [Column(Storage = "_StartAt", CanBeNull = false, DbType = "datetime NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime StartAt
        {
            get
            {
                return this._StartAt;
            }
            set
            {
                if (this._StartAt != value)
                {
                    this.OnStartAtChanging(value);
                    this.SendPropertyChanging();
                    this._StartAt = value;
                    this.SendPropertyChanged("StartAt");
                    this.OnStartAtChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EndAt in the schema.
        /// </summary>
        [Column(Storage = "_EndAt", DbType = "datetime", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> EndAt
        {
            get
            {
                return this._EndAt;
            }
            set
            {
                if (this._EndAt != value)
                {
                    this.OnEndAtChanging(value);
                    this.SendPropertyChanging();
                    this._EndAt = value;
                    this.SendPropertyChanged("EndAt");
                    this.OnEndAtChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
